// This code was autogenerated with `dbus-codegen-rust `, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgFreedesktopDBusProperties {
    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error>;
    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error>;
    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusProperties for blocking::Proxy<'a, C> {

    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Get", (interface_name, property_name, ))
            .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>, )| Ok(r.0, ))
    }

    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "GetAll", (interface_name, ))
            .and_then(|r: (arg::PropMap, )| Ok(r.0, ))
    }

    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Set", (interface_name, property_name, value, ))
    }
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusIntrospectable for blocking::Proxy<'a, C> {

    fn introspect(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&self) -> Result<(), dbus::Error>;
    fn get_machine_id(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusPeer for blocking::Proxy<'a, C> {

    fn ping(&self) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "Ping", ())
    }

    fn get_machine_id(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "GetMachineId", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}

pub trait OrgErikreiderSwayncCc {
    fn get_visibility(&self) -> Result<bool, dbus::Error>;
    fn close_all_notifications(&self) -> Result<(), dbus::Error>;
    fn notification_count(&self) -> Result<u32, dbus::Error>;
    fn toggle_visibility(&self) -> Result<(), dbus::Error>;
    fn toggle_dnd(&self) -> Result<bool, dbus::Error>;
    fn set_dnd(&self, state: bool) -> Result<(), dbus::Error>;
    fn get_dnd(&self) -> Result<bool, dbus::Error>;
    fn close_notification(&self, id: u32) -> Result<(), dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgErikreiderSwayncCc for blocking::Proxy<'a, C> {

    fn get_visibility(&self) -> Result<bool, dbus::Error> {
        self.method_call("org.erikreider.swaync.cc", "GetVisibility", ())
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn close_all_notifications(&self) -> Result<(), dbus::Error> {
        self.method_call("org.erikreider.swaync.cc", "CloseAllNotifications", ())
    }

    fn notification_count(&self) -> Result<u32, dbus::Error> {
        self.method_call("org.erikreider.swaync.cc", "NotificationCount", ())
            .and_then(|r: (u32, )| Ok(r.0, ))
    }

    fn toggle_visibility(&self) -> Result<(), dbus::Error> {
        self.method_call("org.erikreider.swaync.cc", "ToggleVisibility", ())
    }

    fn toggle_dnd(&self) -> Result<bool, dbus::Error> {
        self.method_call("org.erikreider.swaync.cc", "ToggleDnd", ())
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn set_dnd(&self, state: bool) -> Result<(), dbus::Error> {
        self.method_call("org.erikreider.swaync.cc", "SetDnd", (state, ))
    }

    fn get_dnd(&self) -> Result<bool, dbus::Error> {
        self.method_call("org.erikreider.swaync.cc", "GetDnd", ())
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn close_notification(&self, id: u32) -> Result<(), dbus::Error> {
        self.method_call("org.erikreider.swaync.cc", "CloseNotification", (id, ))
    }
}

#[derive(Debug)]
pub struct OrgErikreiderSwayncCcSubscribe {
    pub count: u32,
    pub dnd: bool,
}

impl arg::AppendAll for OrgErikreiderSwayncCcSubscribe {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.count, i);
        arg::RefArg::append(&self.dnd, i);
    }
}

impl arg::ReadAll for OrgErikreiderSwayncCcSubscribe {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgErikreiderSwayncCcSubscribe {
            count: i.read()?,
            dnd: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgErikreiderSwayncCcSubscribe {
    const NAME: &'static str = "Subscribe";
    const INTERFACE: &'static str = "org.erikreider.swaync.cc";
}
