[package]
name = "waybar"
version = "0.1.0"
authors = ["Adam Harvey <adam@adamharvey.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
miniserde = "0.1.14"
